puravidaviajespremium/CLIENT

- src/App.jsx
> el cambiazo

- src/App.css
- src/components/Footer/Footer.jsx
- src/components/Footer/Footer.module.css
Cambie color al footer y agregue el Logo de la empresa
> Dandole forma al footer

- package-lock.json
- package.json
- src/App.css
- src/components/Carrusel/CarruselContainer.jsx
- src/components/Carrusel/ItemCarrusel/ItemCarrusel.jsx
- src/components/Carrusel/ItemCarrusel/itemCarrusel.css
- src/components/Carrusel/carruselContainer.css
- src/views/Home/Home.jsx
> HOME-01-Carrusel Destinos destacados

- src/App.css
- src/components/Footer/Footer.module.css
- src/views/Detail/Detail.jsx
- src/views/Detail/Detail.module.css
Corregí el diseño responsive de mobile a desktop, sección de experiencias interactivo.
> Detail responsive

- src/views/Detail/Detail.module.css
Corregi el tamaño de las imagenes de las experiencias.
> Corrigiendo tamaño de imagenes

- src/components/Footer/Footer.jsx
- src/components/Information/Information.jsx
- src/components/Information/Information.module.css
- src/views/Detail/Detail.jsx
- src/views/Home/Home.jsx
Componente de informacion de la empresa.
Coloque una imagen de fondo y los 3 valores de la empresa.
> creacion del componente de information

- src/components/Encabezado/Encabezado.module.css
- src/components/Information/Information.jsx
- src/components/Information/Information.module.css
- src/redux/slices/countriesSlice.js
- src/views/Detail/Detail.module.css
- src/views/Home/Home.jsx
Agregue el effecto Parallax a la sección de los valores de la Empresa
> Information con Parallax

- src/components/Information/Information.jsx
- src/components/Information/Information.module.css
Corregi el tamaño de los icons
> modificando el tamaño de los icons

- src/components/Information/Information.jsx
- src/components/Information/Information.module.css
Agregue opacidad a la imagen para resaltar mas los valores de la empresa
> Terminando componente Information

- src/redux/actions/countriesActions.js
Arregle conflicto de sintaxis entre las actions.
> Fix countriesActions

- src/redux/actions/clientsActions.js
- src/redux/slices/clientsSlices.js
- src/redux/store/store.js
- src/views/Contact/Contact.jsx
- src/views/Contact/Contact.module.css
- src/views/Contact/validate.js
- Validaciones front del formulario
- Se implementó Redux para el formulario. (POST)
> Formulario de contacto

- src/components/Information/Information.module.css
- src/redux/actions/countriesActions.js
- src/redux/slices/countriesSlice.js
- src/views/Detail/Detail.jsx
- src/views/Detail/Detail.module.css
Aguegue una action para que al desmontar el componente del Detail, se limpie el estado de detail y no quede la información de otro pais anteriormente visto.
> Agregue action para limpiar Detail

- src/views/Detail/Detail.module.css
Ajuste el tamaño del contenedor de la descripcion de los paises.
Agrande la imagen y le di transparencia al contenedor para apreciar mas la imagen de fondo.
> ajustando tamaños de los contenedores por descripciones

- src/components/Promocion/Promocion.jsx
- src/components/Promocion/Promocion.module.css
- src/views/Home/Home.jsx
Agregue el componente Promoción
> Agregue el Componente Promocion

- src/views/Destinations/Destinations.jsx
Agregue el atributo id al CountryCard mapeado en Destination para que le llegue por props a ese componente y pueda ingresar al detalle del pais desde la vista de Destinos
> fix detail desde destinos

- src/components/Promocion/Promocion.module.css
Achiqué el espaciado entre los banners
> fix espaciado banners

- src/components/Carrusel/ItemCarrusel/ItemCarrusel.jsx
- src/components/Carrusel/ItemCarrusel/itemCarrusel.css
- src/components/Carrusel/carruselContainer.css
- src/views/Detail/Detail.jsx
- src/views/Detail/Detail.module.css
Realice las modificaciones post demo con Gustavo, cambiando el tamaño y disposición de las tarjetas de los destinos mas destacados y sus descripciones.
> fix componente Detail y destinos

- src/views/Detail/Detail.jsx
- src/views/Detail/Detail.module.css
ultima modificación del detail
> ultima modificación del detail

- src/views/Detail/Detail.module.css
Limpiando codigo css del componente Detail
> Limpiando codigo css

- src/views/Detail/Detail.jsx
Borre etiquetas que ya no utilizo por las modificaciones realizadas
> Detail listo

- package-lock.json
- package.json
- src/components/FormContact/FormContact.jsx
- src/components/FormContact/FormContact.module.css
- src/components/FormContact/validate.js
- src/components/Slider/Slider.css
- Validación input teléfono, e identificar el país de origen del cliente.
- Campo para seleccionar el país de interés.
> Requerimientos post-demo1  Formulario de Contacto

- package-lock.json
- package.json
- src/App.css
- src/redux/actions/clientsActions.js
- Se desarrolló el modal de éxito(cuenta también con una sección para contratar experto) y error para contemplar el envío de información del cliente desde el formulario de contacto.
> Modal exito/error en formulario de contacto

- src/components/Reviews/Reviews.jsx
- src/components/Reviews/Reviews.module.css
- src/components/StepsBanner/StepsBanner.module.css
- src/views/Destinations/Destinations.jsx
- vite.config.js
Código tarjeta trello: 06-Mel/Alan Reviews
Reporte:
1. Se agregó un componente Reviews
2. Se hizo un axios get a la api Places de Google, se usó un id places de una agencia de viajes de ejemplo y renderice la respuesta con lo que necesitaba mostrar. 
Problemas:
Esta peticion a la api se tiene que manejar en el back, porque sino la api arroja un error de Cors que tuve que solucionar momentaneamente con un proxy pero lo que se hizo fue sólo para avanzar la pre-demo.
Nota: Este componente CONTINÚA EN DESARROLLO
Adjunto imágenes de la response en consola y de la vista del componente aunque los estilos son sólo para mostrar algo medianamente prolijo para la demo de hoy con la Instructora.
> Melodi balossino- Feat/Reviews

- src/App.css
- Update Estilos generales del botón primario.
> btnPrimary

- src/App.css
- src/redux/actions/clientsActions.js
- src/utils/modalResults.js
- src/utils/sendEmail.js
- Se crearon dos funciones para modularizar los modales de éxito y error.
- Se realizó la conexión al endpoint de envío de correo desde el formulario de contacto.
> Envío de email desde Formulario de contacto

- src/components/Information/Information.module.css
- src/components/Promocion/Promocion.module.css
- src/views/Detail/Detail.module.css
Modifiqué estilos para unificar criterios en css
> Fix diseño general con estilos predeterminados en App.css

- package-lock.json
- package.json
- src/components/Header/Header.jsx
- src/components/LoginButton/LoginButton.jsx
- src/components/LoginButton/LoginButton.module.css
- src/components/LogoutButton/LogoutButton.jsx
- src/components/LogoutButton/LogoutButton.module.css
- src/components/UserMenu/UserMenu.jsx
- src/components/UserMenu/UserMenu.module.css
- src/main.jsx
Realice la configuración de Auth0 en el front.
Agregue los siguientes componentes:
- LoginButton
- LogoutButton
- UserMenu: menu desplegable con (mail del usuario registrado, Historial de pagos, Boton para cerrar sesion)
> Autenticación y menu

- package-lock.json
- package.json
- src/components/LogoutButton/LogoutButton.jsx
- src/components/PaypalCheckoutButton/PaypalCheckoutButton.jsx
- src/components/UserMenu/UserMenu.jsx
- src/redux/actions/clientsActions.js
- src/utils/modalResults.js
- src/views/Contact/Contact.jsx
- src/views/Destinations/Destinations.jsx
- src/views/Detail/Detail.jsx
- src/views/FAQs/Faqs.jsx
- src/views/Home/Home.jsx
Agregue el renderizado condicional para que el usuario ingrese a su sesion y pueda ir a pagar a paypal
Scroll automatico en todas las vistas para que suba el scroll cuando se monta el componente.
> renderizado condiciona Auth0 y scroll automatico

- src/App.css
- src/components/FormContact/FormContact.jsx
- Se cambio el nombre del estado local para capturar el campo 'País de destino' en formulario de contacto.
> Fix name= destinationCountry en Formulario de contacto

- src/components/FeaturedSection/FeaturedSection.module.css
- src/components/Information/Information.module.css
- src/components/SliderDestinations/SliderDestinations.jsx
- src/components/StepsBanner/StepsBanner.module.css
Arregle algunos margenes y paddings sobrantes
> fix estilos css general

- src/App.jsx
- src/views/CheckoutPayment/CheckoutPayment.module.css
- src/views/CheckoutPayment/PaymentCancel/PaymentCancel.jsx
- src/views/CheckoutPayment/PaymentCancel/PaymentCancel.module.css
- src/views/CheckoutPayment/PaymentSuccess/PaymentSuccess.jsx
- Se agrego una nueva vista de pago cancelado que redirecciona en 3s a la pagina de pago al experto
> Correccion de rutas de imagen/ nueva vista de pago cancelado

- src/App.css
- src/components/LoginButton/LoginButton.jsx
- src/components/LogoutButton/LogoutButton.jsx
- src/components/PaypalCheckoutButton/PaypalCheckoutButton.jsx
- src/components/StepsBanner/StepsBanner.jsx
- src/components/UserMenu/UserMenu.jsx
- src/redux/actions/clientsActions.js
- src/utils/modalResults.js
- src/views/CheckoutPayment/CheckoutPayment.module.css
- src/views/Home/Home.jsx
Bugs Auth0 - Paypal -ModalError
> Bugs Auth0 - Paypal -ModalError

- src/components/Dashboard/Clients/Create/CreateClient.jsx
- src/components/Dashboard/Clients/Edit/EditClients.jsx
- src/components/Dashboard/Clients/List/ListClients.jsx
- src/components/Dashboard/Countries/Create/CreateCountry.jsx
- src/components/Dashboard/Countries/Create/validate.js
- src/components/Dashboard/Countries/Edit/EditCountry.jsx
- src/components/Dashboard/Countries/List/ListCountries.jsx
- src/components/Dashboard/Design/Menu/MyMenu.jsx
- src/components/Dashboard/Design/TopBar/TopBar.jsx
- src/components/Dashboard/Users/Create/CreateUser.jsx
- src/components/Dashboard/Users/Edit/EditUser.jsx
- src/components/Dashboard/Users/List/ListUsers.jsx
- src/components/Dashboard/utils/styleDashboard.css
- Estilos generales(v1) del dashboard (responsive).
- Modificación de algunas estructuras del jsx (Agregar, Lista, Editar)
> style v1 dashboard-responsive

- src/components/Dashboard/Users/Metrics/Cards/Cards.jsx
- src/components/Dashboard/Users/Metrics/ChartBar/ChartBar.jsx
- src/components/Dashboard/Users/Metrics/MetricsDetail/MetricsDetail.jsx
conexión metricas con la ruta metrics :)
> conexión metricas con la ruta metrics

- src/components/Dashboard/Clients/List/ListClients.jsx
- src/views/AdminPanel/AdminPanel.jsx
Renderizado condicional del noton delete para que el Colaborador no pueda eliminar clientes.
> renderizado condicional boton delete cliente

- src/components/Dashboard/Clients/List/ListClients.jsx
- src/components/Dashboard/Clients/List/renderFunctions.jsx
- src/components/Dashboard/Countries/Edit/EditCountry.jsx
- src/components/Dashboard/Countries/Edit/validateEditCountry.js
- src/components/Dashboard/utils/styleDashboard.css
Agrego etiquetas de membresia y estado de contacto en la lista de clientes del dashboard :)
> Feat-Etiquetas-clientes

- src/components/Dashboard/Design/Menu/MyMenu.jsx
- src/components/Dashboard/utils/styleDashboard.css
- src/components/Header/Header.jsx
- src/components/UserMenu/UserMenu.module.css
- src/views/AdminPanel/AdminPanel.jsx
Acomode el logo del usuario logueado a la derecha y el menu desplegable.
Renderizado condicional de las resources para que le muestre sólo el de Clientes al Colaborador y todas al Administrador
> logo usuario, renderizado resources listo

- src/components/Dashboard/Countries/Create/CreateCountry.jsx
- src/components/Dashboard/utils/styleDashboard.css
> Fix estilos de  Destinos en Form de Creación/Edición

- src/components/Dashboard/Clients/Edit/EditClients.jsx
- src/components/Dashboard/Clients/Edit/validateEditClient.js
- src/components/Dashboard/Users/Metrics/Cards/Cards.css
- src/components/Dashboard/Users/Metrics/Cards/Cards.jsx
- src/components/Dashboard/Users/Metrics/ChartBar/ChartBar.css
- src/components/Dashboard/Users/Metrics/ChartBar/ChartBar.jsx
- src/components/Dashboard/Users/Metrics/MetricsDetail/MetricsDetail.css
- src/components/Dashboard/Users/Metrics/MetricsDetail/MetricsDetail.jsx
Dejo los estilos de las métricas :)
> Styles-Metrics

- src/components/Dashboard/Countries/Create/validate.js
- src/components/Dashboard/Countries/Edit/validateEditCountry.js
- src/components/FormContact/FormContact.jsx
> Validate formulario de creación/edición país

- src/components/Dashboard/utils/styleDashboard.css
Se editan los estilos de las etiquetas (tamaños) :)
> EstilosEtiquetas
